# Generated by Django 5.1.5 on 2025-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('image_word', 'Imagen y palabra'), ('sound_image', 'Sonido e imagen'), ('word_matching', 'Emparejar palabras'), ('dictation', 'Dictado'), ('letter_recognition', 'Reconocimiento de letras'), ('pronunciation', 'Pronunciación')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='activities/sounds/')),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
    ]
