# Generated by Django 5.1.5 on 2025-04-08 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstProject', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sound_file',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
    ]
